[package]
name = "calicostrs"
version = "0.1.0"
edition = "2021"

[lib]
name = "calicostem"
crate-type = ["cdylib"]

[dependencies]
statrs = "0.15.0"
rayon = "1.5.1"
pyo3 = { version = "0.19.0", features = ["extension-module"] }
numpy = { version = "*" }
ndarray = {version = "*" }